name: easy_entry
description: A simple, readable and concise way to deal with modifying, inserting and removing Map entries in Dart.
version: 1.0.1
repository: https://github.com/cds-reis/easy_entry.git

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
