name: easy_entry
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/cds-reis/easy_entry.git

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
